// Preguntas de "A ciegas". Cada día toca una, la misma para todo el mundo.
// `demo`: respuestas de ejemplo que usan los perfiles demo.

export const BLIND_QUESTIONS = [
  {
    id: 'superpoder_inutil',
    text: '¿Qué superpoder completamente inútil te encantaría tener?',
    demo: [
      'Saber siempre cuál es la cola más rápida del súper.',
      'Que las tostadas nunca caigan por el lado de la mantequilla.',
      'Encontrar el borde del celo a la primera.',
      'Calentar el café solo con mirarlo.',
      'Recordar dónde dejé las llaves (eso es casi magia).',
      'Hablar con las palomas. Seguro que tienen mucho que contar.',
    ],
  },
  {
    id: 'banda_sonora',
    text: 'Si tu vida tuviera banda sonora, ¿qué canción sonaría ahora mismo?',
    demo: [
      'Algo de Rosalía: caos bonito.',
      '"Here Comes the Sun". Vengo de un invierno largo.',
      'Una de Bad Bunny para fingir que todo está bajo control.',
      'Jazz suave mientras intento tener la vida en orden.',
      'La de los créditos de una peli de Pixar: emocional pero esperanzadora.',
      'Cualquier cosa de Coldplay, estoy en modo optimista.',
    ],
  },
  {
    id: 'cena_tres',
    text: 'Cena con tres personas (vivas o no). ¿A quién invitas?',
    demo: [
      'Frida Kahlo, mi abuela y alguien que cocine bien para que nadie pase hambre.',
      'García Márquez, Shakira y mi yo de 10 años.',
      'Carl Sagan, Celia Cruz y alguien que sepa de vinos.',
      'Mi bisabuela, Einstein y Lola Flores. Caos asegurado.',
      'Cervantes, para preguntarle si esperaba tanto éxito, y dos amigas que se rían mucho.',
      'David Attenborough, Rosalía y mi perro (sí, cuenta).',
    ],
  },
  {
    id: 'pequeno_placer',
    text: '¿Cuál es ese pequeño placer tuyo que nadie entiende?',
    demo: [
      'El olor de los libros nuevos. Los huelo antes de leerlos.',
      'Pelar una mandarina en una sola pieza.',
      'Ir al cine sin compañía un martes por la tarde.',
      'Ordenar las especias por colores.',
      'Despertarme antes de la alarma y saber que puedo dormir 10 minutos más.',
      'Hacer listas de cosas que nunca voy a hacer.',
    ],
  },
  {
    id: 'mejor_consejo',
    text: '¿Cuál es el mejor consejo que te han dado?',
    demo: [
      'Que no tome decisiones importantes con hambre.',
      '"Lo que no te cuesta hoy, te costará mañana". Mi abuelo.',
      'Que pregunte siempre "¿y tú qué opinas?".',
      'Si dudas entre ir o no ir a un viaje: ve.',
      'Quien de verdad te quiere no te hace dudar de si le importas.',
      'Bebe agua. En serio, arregla la mitad de los problemas.',
    ],
  },
  {
    id: 'domingo_lluvia',
    text: 'Domingo, llueve y no hay planes. ¿Qué haces?',
    demo: [
      'Manta, sopa y una saga entera de películas.',
      'Salgo a caminar bajo la lluvia, me encanta.',
      'Cocino algo que tarde horas, solo por el olor.',
      'Llamo a alguien y montamos una tarde de juegos de mesa.',
      'Leo hasta dormirme en el sofá. Plan perfecto.',
      'Por fin ordeno ese cajón… o no.',
    ],
  },
  {
    id: 'viaje_tiempo',
    text: 'Si pudieras viajar en el tiempo una sola vez, ¿a cuándo irías?',
    demo: [
      'Al concierto de Queen en Wembley del 86.',
      'Cien años al futuro, solo para ver si al final hubo coches voladores.',
      'Al día en que se conocieron mis padres.',
      'A la Roma antigua, pero solo un ratito.',
      'A mi primer día de universidad, para decirme que me relaje.',
      'A los 90, para vivir los conciertos sin móviles.',
    ],
  },
  {
    id: 'red_flag',
    text: '¿Cuál es tu "red flag" más inofensiva?',
    demo: [
      'Leo el final de los libros primero.',
      'Tengo 47 pestañas abiertas y todas son importantes.',
      'Les pongo nombre a mis plantas.',
      'Contesto los audios con audios más largos.',
      'Me río de mis chistes antes de terminarlos.',
      'Pongo cinco alarmas cada mañana.',
    ],
  },
  {
    id: 'sonrisa_hoy',
    text: '¿Qué te ha hecho sonreír hoy?',
    demo: [
      'Un perro me ha mirado como si me conociera de toda la vida.',
      'El primer sorbo de café de la mañana.',
      'Un mensaje de mi madre con demasiados emojis.',
      'Ha sonado mi canción favorita en el súper.',
      'Ver a dos señores mayores bailando en la plaza.',
      'Que el autobús llegó justo cuando llegaba yo.',
    ],
  },
  {
    id: 'aprender',
    text: '¿Qué aprenderías si tuvieras tiempo infinito?',
    demo: [
      'A tocar el piano como en las películas.',
      'Japonés, para ver anime sin subtítulos.',
      'Cerámica. Quiero mis propias tazas.',
      'A navegar a vela y dar la vuelta al mundo.',
      'Carpintería: construir algo con mis manos.',
      'A bailar salsa sin pisar a nadie.',
    ],
  },
  {
    id: 'plato_eterno',
    text: 'Solo puedes comer un plato el resto de tu vida. ¿Cuál?',
    demo: [
      'Tortilla de patatas. Con cebolla, sin debate.',
      'Tacos al pastor, sin dudarlo.',
      'Arepas rellenas de todo.',
      'Ceviche bien picante.',
      'Carbonara (la de verdad, sin nata).',
      'Ramen. Es un abrazo en un bol.',
    ],
  },
  {
    id: 'valiente',
    text: '¿Qué es lo más valiente que has hecho?',
    demo: [
      'Mudarme a otro país sin conocer a nadie.',
      'Dejar un trabajo estable para dedicarme a lo que me gusta.',
      'Decir "te quiero" primero.',
      'Hacer puenting… gritando todo el rato.',
      'Pedir ayuda cuando la necesitaba.',
      'Cantar en una boda delante de 200 personas.',
    ],
  },
  {
    id: 'anecdota_cita',
    text: '¿Cuál es la anécdota más divertida que te ha pasado en una cita?',
    demo: [
      'Me tiré el café encima en los primeros cinco minutos. Acabamos riéndonos dos horas.',
      'Nos equivocamos de sala en el cine y vimos una de terror en vez de una comedia.',
      'Llovió tanto que nos refugiamos en una librería. Lo mejor de la noche.',
      'Resultó que conocía a toda su familia del pueblo. Mundo pequeño.',
      'Nos perdimos buscando un restaurante y acabamos comiendo pizza en un banco.',
      'El camarero pensó que llevábamos años juntos. Era nuestra segunda cita.',
    ],
  },
  {
    id: 'lugar_feliz',
    text: 'Describe tu lugar feliz en pocas palabras.',
    demo: [
      'Una playa vacía a las 8 de la mañana.',
      'La cocina de mi abuela un domingo.',
      'Cualquier mirador después de una buena subida.',
      'Una librería pequeña con gato incluido.',
      'Un concierto en primera fila.',
      'Mi balcón con plantas y un café.',
    ],
  },
  {
    id: 'polemica',
    text: 'Defiende una opinión polémica (pero inofensiva).',
    demo: [
      'Primero los cereales y luego la leche. Siempre.',
      'Los lunes no son tan malos: son un nuevo comienzo.',
      'La mejor parte de la pizza es el borde.',
      'Las películas de Navidad se pueden ver en julio.',
      'Dormir con calcetines es lo mejor.',
      'El descafeinado tiene su encanto.',
    ],
  },
  {
    id: 'apodo',
    text: '¿Qué apodo te pondrían tus amistades y por qué?',
    demo: [
      '"La brújula", porque siempre sé dónde se come bien.',
      '"GPS", porque nunca me pierdo… casi nunca.',
      '"Wikipedia", por los datos inútiles que suelto en las cenas.',
      '"DJ", porque secuestro la música en todas las fiestas.',
      '"Modo avión", porque a las 11 ya estoy en la cama.',
      '"Terapia", porque todo el mundo me cuenta sus dramas.',
    ],
  },
  {
    id: 'recomendacion',
    text: '¿Qué libro, serie o peli recomendarías a todo el mundo?',
    demo: [
      '"Cien años de soledad". Se lee una vez y se recuerda siempre.',
      '"The Office". Mi serie de consuelo.',
      '"Coco". Lloré y no me arrepiento.',
      '"Dark". Te explota la cabeza en el mejor sentido.',
      'Cualquier libro de Isabel Allende.',
      '"Ted Lasso". Te reconcilia con la humanidad.',
    ],
  },
  {
    id: 'agradeces',
    text: '¿Qué pequeña cosa agradeces hoy?',
    demo: [
      'Las amistades que escriben solo para saber cómo estoy.',
      'Que mi planta por fin ha sacado una hoja nueva.',
      'Un día de sol después de una semana gris.',
      'La siesta de hoy. Gloriosa.',
      'Haber probado un restaurante nuevo con mi hermana.',
      'Mi salud, que no siempre valoro.',
    ],
  },
  {
    id: 'dia_libre',
    text: 'Mañana te regalan un día libre sorpresa. ¿Cómo lo usas?',
    demo: [
      'Tren a la playa más cercana y móvil en modo avión.',
      'Maratón de museos y luego tapas.',
      'Dormir hasta tarde y desayunar a mediodía.',
      'Ir a ver a mis abuelos.',
      'Una ruta en bici sin rumbo.',
      'Cocinar para mis amigos y alargar la sobremesa hasta la noche.',
    ],
  },
  {
    id: 'conexion',
    text: '¿Cuál es para ti la señal de que conectas de verdad con alguien?',
    demo: [
      'Cuando el silencio no es incómodo.',
      'Cuando se pasan las horas hablando sin darte cuenta.',
      'Cuando os reís de lo mismo sin explicarlo.',
      'Cuando te acuerdas de esa persona al escuchar una canción.',
      'Cuando puedes ser tú sin filtro.',
      'Cuando te pregunta por algo que le contaste hace semanas.',
    ],
  },
  {
    id: 'plato_estrella',
    text: '¿Cuál es tu plato estrella cuando quieres impresionar?',
    demo: [
      'Risotto de setas. Paciencia y amor.',
      'Tacos caseros con tortillas hechas a mano.',
      'Unas lentejas que resucitan a cualquiera.',
      'Tarta de queso. Infalible.',
      'Pasta fresca, aunque la cocina acabe hecha un desastre.',
      'Pido a domicilio, pero con mucho estilo.',
    ],
  },
];

export const blindQuestionById = new Map(BLIND_QUESTIONS.map((q) => [q.id, q]));
